---
title: "Publications"
format: html
engine: knitr
---

```{css}
#| echo: false
p {
  text-align: justify
}
```

**1.	Book / Book Chapter**

1.	Çetin M., **Kaya E.**, Bozdoğan Sert E., 2021. Bina Kat Yüksekliklerinin Belirlenmesinde Openstreetmap Verilerinin Kullanılabilirliğinin Araştırılması: İskenderun Örneği, Kent Araştırmaları, Editör: Doç. Dr. Şenay GÜNGÖR; Öğr. Gör. Dr. Fatih ADIGÜZEL, Basım sayısı:1, Sayfa sayısı:330, ISBN:978-625-7606-34-9, Bölüm Sayfaları:77 -84

2.	Çetin M., **Kaya E.**, 2021. İklim ve Planlama, Yayın Yeri: PEGEM Akademi, Editör: Prof. Dr. Mesut DOĞAN; Dr. Öğr. Üyesi Mustafa KÖSE; Dr. Öğr. Üyesi Fatih AYHAN, Basım sayısı:1, Sayfa sayısı:327, ISBN:978-625-7582-51-3, Bölüm Sayfaları:281 -293

3.	Çetin M., **Kaya E.**, Bozdoğan Sert E., Güzel Z. T., Adıgüzel F., Güngör Ş., 2020. Determining the Impact of Various Surfaces in Open Green Areas of Iskenderun Coastal Band on Thermal Comfort, St. Kliment Ohridski University Press, Editör: Ilia CHRISTOV, Viliyan KRYSTEV, Recep EFE, Abd Alla GAD, Press:1, ISBN:978-954-07-5047-7, Section Pages:194 -211

4.	**Kaya E.**, Adıgüzel F., 2020. Nevşehir İli Yüzey Analizlerinin R Programlama Dili ile Yapılması ve 3B Boyutlu Görselleştirilmesi, Kapadokya Araştırmaları İnsan ve Mekân, Sayfa: 141-153 ISBN 978-605-337-267-7, Mart 2020

5.	**Kaya E.**, Erener A., 2018. Automatic Building and Height Determination from Unmanned Aerial Vehicle Data, Advances in Remote Sensing and Geo Informatics Applications, DOI: https://doi.org/10.1007/978-3-030-01440-7, ISBN:978-3-030-01439-1


**2.	Peer-Reviewed Journal Articles**

1.	Ağca, M., **Kaya, E.**, Daloğlu, A. İ., Yücel, A., Yalçınkaya, S. 2024. Obtaining tree height information in urban areas from ICESat-2/ATLAS and UAV data. Geomatik, 9 (1), 86-96. https://doi.org/10.29128/geomatik.1384320.

2.	**Kaya, E.**, Erener, A. 2024. UAV-mounted thermal camera and its analysis on urban surface textures. International Journal of Engineering and Geosciences, 9 (1), 49-60. https://doi.org/10.26833/ijeg.1288990.

3.	**Kaya, E.** 2023. Evaluation of bioclimatic comfort area with heat index: A case study of Kocaeli, International Journal of Engineering and Geosciences, 8 (1), 19-25. DOI: 10.26833/ijeg.988452.

4.	**Kaya E.**, Şentürk E., Erener A., Özkul C., Akyol N. H. 2023. SoilSpatvis: WEB Application for Geographical Data Visualization with R Language for Assessing Soil Pollution, Soil and Sediment Contamination: An International Journal, DOI: 10.1080/15320383.2023.2282108.

5.	Adiguzel, F., Cetin, M., Dogan, M., Gungor S., Kose M., Sert Bozdogan E., **Kaya E.** 2022. The assessment of the thermal behavior of an urban park surface in a dense urban area for planning decisions. Environ Monit Assess 194, 519. https://doi.org/10.1007/s10661-022-10172-y.

6.	Adiguzel F., Bozdogan Sert E., Dinc Y., Cetin M., Gungor Ş., Yuka P., Sertkaya Dogan Ö., **Kaya E.**, Karakaya K., Vural E. 2021. Determining the relationships between climatic elements and thermal comfort and tourism activities using the tourism climate index for urban planning: a case study of Izmir Province, Theoretical and Applied Climatology, https://doi.org/10.1007/s00704-021-03874-9

7.	Bozdogan Sert, E., **Kaya, E.**, Adiguzel, F., Çetin M., Güngör Ş., Çetin İ. Z., Dinc Y., 2021. Effect of the surface temperature of surface materials on thermal comfort: a case study of Iskenderun (Hatay, Turkey). Theor Appl Climatol (2021). https://doi.org/10.1007/s00704-021-03524-0.

8.	Adıgüzel F., Çetin M., **Kaya E.**, Şimşek M., Güngör Ş., Bozdoğan Sert E. 2020. Defining suitable areas for bioclimatic comfort for landscape planning and landscape management in Hatay, Turkey. Theor Appl Climatol 139, 1493–1503. https://doi.org/10.1007/s00704-019-03065-7.

9.	Çetin M., Adıgüzel F., Güngör Ş., **Kaya E.**, Sancar M.C. 2019. Evaluation of thermal climatic region areas in terms of building density in urban management and planning for Burdur, Turkey, Air Quality Atmosphere and Health.

10.	**Kaya E.**, Agca M., Adiguzel F., Cetin M. 2019. Spatial Data Analysis With R Programming For Environment, Human and Ecological Risk Assessment: An International Journal, DOI: 10.1080/10807039.2018.1470896, https://doi.org/10.1080/10807039.2018.1470896.

11.	**Kaya E.**, Güngör, M. (2021). Numerical data generation usingunmanned aerial vehicle: a case study of Aksaray Güzelyurt District. Advanced UAV, 1(1), 34-39

12.	Ağca, M., **Kaya, E.**, Yılmaz, H. 2020. 3D Modeling Of Cultural Heritages With UAV And TLS Systems: A Case Study On The Somuncu Baba Mosque. ArtGRID-Journal of Architecture Engineering and Fine Arts, 2 (1), 1-12.

13.	Erener A., Aşcı M., Gülsoy G., Üstün A., Güvenaltın M., Şentürk E., Yalvaç S., Canaslan Çomut F., Irmak T.S., Konak H., Küreç Nehbit P. **Kaya E.**, Kotan B., Öye S. (2022). İzmit Körfezi ve Çevresinde Bina Yoğunluk ve Sıvılaşma Yayılımının Mekânsal Analizi. Doğal Afetler ve Çevre Dergisi, 8 (1), 111-121. DOI: 10.21324/dacd.943637

14.	Ağca M., **Kaya E.**, Yılmaz H.M. 2020. Yersel ve Fotogrametrik Yöntemler ile Kaya Bloklarının Hacimlerinin Hesaplanması: Selime Örneği, Aksaray. Afyon Kocatepe Üniversitesi Fen ve Mühendislik Bilimleri Dergisi, 20 (3), 465-471.

15.	Ağca, M., Gültekin, N., **Kaya E.** 2020. İnsansız Hava Aracından Elde Edilen Veriler ile Kaya Düşme Potansiyelinin Değerlendirilmesi: Adam Kayalar Örneği, Mersin. Geomatik, 5 (2), 134-145. DOI: 10.29128/geomatik.595574

16.	Alkan A., Adıgüzel F., **Kaya E.** 2017. Batman Şehrinde Kentsel Isınmanın Azaltılmasında Yeşil Alanların Önemi, İstanbul Üniversitesi Coğrafya Dergisi, 2017 (34) (Basılı) ISNN 1302-7212, (Elektronik) ISNN 1305-2128

**3.	Conference Proceedings**

1.	Ağca M., Yücel A., Daloğlu A. İ., **Kaya E.**, Yetkin M., Yalçın Küçükbayrak F. 2023. Estimation of Building Height From Icesat-2/ATLAS and Airborne Lidar Data Using Machine Learning Algorithms, 2nd International Congress on Innovation Technologies & Engineering, June 12-13, 2023, Ege University, Izmir, Türkiye

2.	Saydan, E., Güngör, Ş., **Kaya, E.** 2021. Changes in Land Use between 1990 and 2018 on the Basis of the Corine System in Adana Province.1st Advanced Engineering Days, p.81-83

3.	**Kaya E.**, Erener A. 2021. Investigation of the Relationship between Bioclimatic Comfort and Building Density: The Case of Kocaeli, Art&Design-2021 International Congress On Art And Design Research And Exhibition, 21-22 June 2021, Niğde

4.	**Kaya E.**, Erener A., Adıgüzel F. 2021. Use of Unmanned Aerial Vehicles in Surface Temperature Mapping: The Case of Hacı Bektaş-ı Veli University, Art&Design-2021 International Congress On Art and Design Research and Exhibition, 21-22 June 2021, Niğde

5.	Erener A., Üstün A., Yalvaç S., Çomut F.C., Şentürk E., **Kaya E.** 2019. Investigation of Time Dependent Building Density and Land Subsidence in the Case of East Marmara (Izmit Bay), (25.09.2019-27.09.2019), VI. International Earthquake Symposium Kocaeli 2019 (IESKO 2019), 2019

6.	**Kaya E.**, Adiguzel F., Gungor Ş., Cetin M. 2019. Point Cloud Data and Using High-Resolution Orthophotos to Remove Auto Building Floor Heights: A Case Study: Adana-Çukurova District, İSTE-CE'2019- International Conference on Innovation, Sustainability, Technology and Education in Civil Engineering, 13-15 June, 2019, Iskenderun, Hatay/TURKEY (Full Text)

7.	**Kaya E.**, Adigüzel F., Çetin M., Avcı T. 2019. The Forming Of Building Density Analysis Maps From The Landsat‐8 Data With The Use Of Machine Learning Algorithms: A Case Study Of Adana City, 1st Istanbul International Geography Congress, 20-22 June 2019, Istanbul (Full Text)

8.	Güngör Ş., Çetin M., Adigüzel F., Deniz A., **Kaya E.** 2019. The Effect of Urben Planning on Urban Formations With Determined The Effect Of Bioclimatic Comfort: A Case Study Of Bursa City, 1st Istanbul International Geography Congress, 20-22 June 2019, Istanbul (Full Text)

9.	Erener A., **Kaya E.** 2018. Automatic Building and Building Height Determination From Unmanned Aerial Vehicle Data, 1st Conference of the Arabian Journal of Geosciences (1st CAJG), 12–15 November, 2018, Hammamet, TUNISIA (Full Text)

10.	**Kaya E.**, Ağca M., Adıgüzel F., Çetin M. 2017. Spatial Data Analysis with R Programming, International Advanced Researches & Engineering Congress-2017, Osmaniye/TURKEY, 16-18 November 2017 (Abstract)

11.	Adıgüzel F., **Kaya E.**, Çerçioğlu M., Çetinkaya D. 2017. Spatial Data Production with Unmanned Aerial Vehicles, International Advanced Researches & Engineering Congress-2017, Osmaniye/TURKEY, 16-18 November 2017 (Abstract)

12.	Adıgüzel F., **Kaya E.**, Çerçioğlu M. 2016. Analysis of Forest Fire Depends On Topographic Features Using by GIS and Remote Sensing Data, TÜCAUM 2016 Uluslararası Coğrafya Sempozyumu, 13-14 Ekim 2016, Ankara Üniversitesi (Abstract)

13.	Alkan A., Adıgüzel F., **Kaya E.** 2016. The Importance Of Green Places in Decreasing The Urban Temperature in Batman, TÜCAUM 2016 Uluslararası Coğrafya Sempozyumu, 13-14 Ekim 2016, Ankara Üniversitesi (Abstract)
